import type { FollowUpTag, UrgencyLevel } from "../utils/followUp";
import type { ReactionSummaryEntry } from "../lib/messageReactions";
import type { ContentType, ContentVisibility } from "./content";
import type { VoiceTranslation } from "./voiceAnalysis";
import type { AgencyIntensity, AgencyPlaybook, AgencyStage } from "../lib/agency/types";

interface Message {
  fanId?: string;
  id?: string;
  me: boolean;
  message: string;
  translatedText?: string | null;
  translationSourceLang?: string | null;
  translationTargetLang?: string | null;
  audience?: "FAN" | "CREATOR" | "INTERNAL";
  seen?: boolean;
  time?: string;
  createdAt?: string;
  status?: "sending" | "failed" | "sent";
  kind?: "text" | "content" | "sticker" | "system" | "audio";
  type?: "TEXT" | "CONTENT" | "STICKER" | "SYSTEM" | "AUDIO" | "VOICE";
  stickerId?: string | null;
  stickerSrc?: string | null;
  stickerAlt?: string | null;
  audioUrl?: string | null;
  audioDurationMs?: number | null;
  audioMime?: string | null;
  audioSizeBytes?: number | null;
  transcriptText?: string | null;
  transcriptStatus?: "OFF" | "PENDING" | "DONE" | "FAILED" | null;
  transcriptError?: string | null;
  transcribedAt?: string | null;
  transcriptLang?: string | null;
  intentKey?: string | null;
  intentConfidence?: number | null;
  intentMeta?: unknown;
  intentUpdatedAt?: string | null;
  intentJson?: {
    intent?: string;
    tags?: string[];
    needsReply?: boolean;
    replyDraft?: string;
  } | null;
  voiceAnalysisJson?: string | null;
  voiceAnalysisUpdatedAt?: string | null;
  voiceTranslation?: VoiceTranslation | null;
  reactionsSummary?: ReactionSummaryEntry[];
  contentItem?: {
    id: string;
    title: string;
    type: ContentType;
    visibility: ContentVisibility;
    externalUrl?: string;
  } | null;
}

interface Conversation {
  id?: string;
  contactName: string;
  displayName?: string | null;
  creatorLabel?: string | null;
  locale?: string | null;
  preferredLanguage?: "es" | "en" | "ro" | null;
  messageHistory: Message[];
  image: string;
  membershipStatus?: string;
  accessState?: "ACTIVE" | "EXPIRED" | "NONE";
  accessType?: string | null;
  accessLabel?: string | null;
  hasActiveAccess?: boolean;
  daysLeft?: number;
  unreadCount?: number;
  isNew?: boolean;
  isNew30d?: boolean;
  lastSeen?: string;
  lastSeenAt?: string | null;
  lastTime?: string;
  followUpTag?: FollowUpTag;
  lastCreatorMessageAt?: string | null;
  lastActivityAt?: string | null;
  lastMessageAt?: string | null;
  notesCount?: number;
  notePreview?: string | null;
  profileText?: string | null;
  quickNote?: string | null;
  followUpOpen?: FanFollowUp | null;
  urgencyLevel?: UrgencyLevel;
  paidGrantsCount?: number;
  lifetimeValue?: number;
  customerTier?: "new" | "regular" | "vip" | "priority";
  nextAction?: string | null;
  nextActionAt?: string | null;
  nextActionNote?: string | null;
  activeGrantTypes?: string[];
  hasAccessHistory?: boolean;
  priorityScore?: number;
  lastNoteSnippet?: string | null;
  nextActionSnippet?: string | null;
  lastNoteSummary?: string | null;
  nextActionSummary?: string | null;
  agencyStage?: AgencyStage | null;
  agencyObjective?: string | null;
  agencyObjectiveLabel?: string | null;
  agencyIntensity?: AgencyIntensity | null;
  agencyPlaybook?: AgencyPlaybook | null;
  agencyNextAction?: string | null;
  agencyRecommendedOfferId?: string | null;
  lifetimeSpend?: number;
  totalSpent?: number;
  recent30dSpent?: number;
  extrasCount?: number;
  extrasSpentTotal?: number;
  tipsCount?: number;
  tipsSpentTotal?: number;
  giftsCount?: number;
  giftsSpentTotal?: number;
  maxExtraTier?: string | null;
  novsyStatus?: "NOVSY" | null;
  isHighPriority?: boolean;
  inviteUsedAt?: string | Date | null;
  highPriorityAt?: string | null;
  segment?: string | null;
  riskLevel?: "LOW" | "MEDIUM" | "HIGH" | string | null;
  healthScore?: number | null;
  temperatureScore?: number | null;
  temperatureBucket?: "COLD" | "WARM" | "HOT" | string | null;
  heatScore?: number | null;
  heatLabel?: "COLD" | "WARM" | "HOT" | string | null;
  heatUpdatedAt?: string | null;
  heatMeta?: unknown;
  lastIntentKey?: string | null;
  lastIntentConfidence?: number | null;
  lastIntentAt?: string | null;
  lastInboundAt?: string | null;
  signalsUpdatedAt?: string | null;
  lastGrantType?: string | null;
  extraLadderStatus?: {
    totalSpent: number;
    lastPurchaseAt: string | null;
    maxTierBought: string | null;
    suggestedTier: string | null;
    phaseLabel: string;
    sessionToday?: {
      todayCount: number;
      todaySpent: number;
      todayHighestTier: string | null;
      todayLastPurchaseAt: string | null;
    } | null;
  } | null;
  extraSessionToday?: {
    todayCount: number;
    todaySpent: number;
    todayHighestTier: string | null;
    todayLastPurchaseAt: string | null;
  } | null;
  needsAction?: boolean;
  nextActionKey?: string | null;
  nextActionLabel?: string | null;
  nextActionText?: string | null;
  nextActionSource?: "reply" | "manual" | "suggested" | "none" | null;
  isBlocked?: boolean;
  isArchived?: boolean;
  isManager?: boolean;
  managerCaption?: string | null;
  firstUtmSource?: string | null;
  firstUtmMedium?: string | null;
  firstUtmCampaign?: string | null;
  firstUtmContent?: string | null;
  firstUtmTerm?: string | null;
}

interface ConversationListData {
  id?: string;
  contactName: string;
  displayName?: string | null;
  creatorLabel?: string | null;
  locale?: string | null;
  preferredLanguage?: "es" | "en" | "ro" | null;
  lastMessage: string;
  lastTime: string;
  image: string;
  messageHistory: Message[];
  membershipStatus?: string;
  accessState?: "ACTIVE" | "EXPIRED" | "NONE";
  accessType?: string | null;
  accessLabel?: string | null;
  hasActiveAccess?: boolean;
  daysLeft?: number;
  unreadCount?: number;
  isNew?: boolean;
  isNew30d?: boolean;
  lastSeen?: string;
  lastSeenAt?: string | null;
  followUpTag?: FollowUpTag;
  lastCreatorMessageAt?: string | null;
  lastActivityAt?: string | null;
  lastMessageAt?: string | null;
  notesCount?: number;
  notePreview?: string | null;
  profileText?: string | null;
  quickNote?: string | null;
  followUpOpen?: FanFollowUp | null;
  urgencyLevel?: UrgencyLevel;
  paidGrantsCount?: number;
  lifetimeValue?: number;
  customerTier?: "new" | "regular" | "vip" | "priority";
  nextAction?: string | null;
  nextActionAt?: string | null;
  nextActionNote?: string | null;
  activeGrantTypes?: string[];
  hasAccessHistory?: boolean;
  priorityScore?: number;
  lastNoteSnippet?: string | null;
  nextActionSnippet?: string | null;
  lastNoteSummary?: string | null;
  nextActionSummary?: string | null;
  agencyStage?: AgencyStage | null;
  agencyObjective?: string | null;
  agencyObjectiveLabel?: string | null;
  agencyIntensity?: AgencyIntensity | null;
  agencyPlaybook?: AgencyPlaybook | null;
  agencyNextAction?: string | null;
  agencyRecommendedOfferId?: string | null;
  lifetimeSpend?: number;
  totalSpent?: number;
  recent30dSpent?: number;
  extrasCount?: number;
  extrasSpentTotal?: number;
  tipsCount?: number;
  tipsSpentTotal?: number;
  giftsCount?: number;
  giftsSpentTotal?: number;
  maxExtraTier?: string | null;
  novsyStatus?: "NOVSY" | null;
  isHighPriority?: boolean;
  inviteUsedAt?: string | Date | null;
  highPriorityAt?: string | null;
  segment?: string | null;
  riskLevel?: "LOW" | "MEDIUM" | "HIGH" | string | null;
  healthScore?: number | null;
  temperatureScore?: number | null;
  temperatureBucket?: "COLD" | "WARM" | "HOT" | string | null;
  heatScore?: number | null;
  heatLabel?: "COLD" | "WARM" | "HOT" | string | null;
  heatUpdatedAt?: string | null;
  heatMeta?: unknown;
  lastIntentKey?: string | null;
  lastIntentConfidence?: number | null;
  lastIntentAt?: string | null;
  lastInboundAt?: string | null;
  signalsUpdatedAt?: string | null;
  lastGrantType?: string | null;
  extraLadderStatus?: {
    totalSpent: number;
    lastPurchaseAt: string | null;
    maxTierBought: string | null;
    suggestedTier: string | null;
    phaseLabel: string;
    sessionToday?: {
      todayCount: number;
      todaySpent: number;
      todayHighestTier: string | null;
      todayLastPurchaseAt: string | null;
    } | null;
  } | null;
  extraSessionToday?: {
    todayCount: number;
    todaySpent: number;
    todayHighestTier: string | null;
    todayLastPurchaseAt: string | null;
  } | null;
  needsAction?: boolean;
  nextActionKey?: string | null;
  nextActionLabel?: string | null;
  nextActionText?: string | null;
  nextActionSource?: "reply" | "manual" | "suggested" | "none" | null;
  isBlocked?: boolean;
  isArchived?: boolean;
  isManager?: boolean;
  managerCaption?: string | null;
  firstUtmSource?: string | null;
  firstUtmMedium?: string | null;
  firstUtmCampaign?: string | null;
  firstUtmContent?: string | null;
  firstUtmTerm?: string | null;
  unseenPurchaseCount?: number;
  unseenPurchaseLabel?: string | null;
}

interface FanFollowUp {
  id: string;
  title: string;
  note?: string | null;
  dueAt?: string | null;
  status: "OPEN" | "DONE" | "DELETED";
  createdAt?: string | null;
  updatedAt?: string | null;
  doneAt?: string | null;
}

export type { Message, Conversation, ConversationListData }
